knp_snappy:
    pdf:
        enabled: true
        binary: '%env(WKHTMLTOPDF_PATH)%'
        options:
            encoding: 'UTF-8'
            margin-top: 12
            margin-bottom: 12
            margin-left: 10
            margin-right: 10
            print-media-type: true
            enable-local-file-access: true
